kind: pipeline
type: docker
name: default

environment:
  author_name: kjcodeacct
  process_name: layover

steps:
  - name: build
    image: golang
    commands:
      - go build
      - go test -p 1 ./...

  - name: build release binaries
    image: golang
    commands:
      - make binaries
    when:
      event: tag

  - name: publish release binaries
    image: plugins/github-release
    settings:
      api_key:
        from_secret: github_api_key
      files: binaries/*.tar.gz
    checksum:
      - sha256
    when:
      event: tag

  - name: docker push
    image: plugins/docker
    settings:
      username: ${author_name}
      password: docker_api_key
      repo: ${author_name}/process_name
      tags: latest
    when:
      event: tag
